### PR TITLE
update property support for fields

### PR DESCRIPTION
**Pull request by travisturner**

### CODE REVIEW

**Review by jaffee — APPROVED** [review]
that insertProps function is a bit scary, but I'm guessing you have a good reason not marshal them in some other way?

**Comment by travisturner** [comment]
yeah, @alanbernstein and I talked about that already. I don't like this bytes insertion either.
I have a follow up to see if we can marshal the custom properties as a nested attribute in the avro field.
so instead of this:
```
{"type": "bytes", "fieldType": "decimal", "scale": 2}
```
we would have something this:
```
{"type": "bytes", "props": {"fieldType": "decimal", "scale": 2}}
```
this was just an attempt to stick to the avro specs, but i would imagine we could nest things.

**Comment by alanbernstein** [comment]
Should we be updating tests here?

**Comment by travisturner** [comment]
yeah, we should. i haven't run the tests on this fork.

**Review by alanbernstein — APPROVED** [review]

**Comment by travisturner** [comment]
oops, i didn't mean to merge this.
you guys can look at the last two commits in the `props-on-primitives` branch, but basically i just removed that ugly byte manipulation code:
392fcc0db3b8f2f7e85f9e3b632d5dae7f41b73b
bc1bf9fd41c10182dfc07cf67e3591afca0a2a9c
@alanbernstein @jaffee

**Pull request merged**
